try{
    console.log("aa");
}
catch(err){
    console.log("aa");
}
