try {
  console.log("aa");
} catch (err) {
  console.log("aa");
}

try {
  console.log("aa");
} catch {
  console.log("aa");
}
